apiVersion: v1
kind: Service
metadata:
  name: traefik
  namespace: traefik-system
  labels:
    app.kubernetes.io/name: traefik
    app.kubernetes.io/component: infrastructure
  annotations:
    external-dns.alpha.kubernetes.io/hostname: traefik.nonprod.internal
spec:
  type: LoadBalancer
  ports:
    - port: 80
      name: web
      targetPort: web
      protocol: TCP
    - port: 443
      name: websecure
      targetPort: websecure
      protocol: TCP
  selector:
    app.kubernetes.io/name: traefik
---
apiVersion: v1
kind: Service
metadata:
  name: traefik-dashboard
  namespace: traefik-system
  labels:
    app.kubernetes.io/name: traefik
    app.kubernetes.io/component: infrastructure
spec:
  type: ClusterIP
  ports:
    - port: 8080
      name: admin
      targetPort: admin
      protocol: TCP
  selector:
    app.kubernetes.io/name: traefik
